on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push the tags back
      id-token: write # Required for npm provenance
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - run: npm version "$(npx utc-version)"
      - run: npm install
      - run: npm publish --workspaces --provenance --access public
      - run: git push origin --tags
